stages:
  - init

job:
  stage: init
  script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://162.241.219.155/public_html/
